### ISSUE TITLE
Create a separate pipeline for production deployment

### ISSUE THREAD

**Issue by VadimGush** [gush-labs/kazan#108]
I have a suspicion that the main cost of running Kazan in the cloud will come from the deployment itself (it seems like every time Cloud Function is updated, Google Cloud uses Compute Engine to build a new image which leads to additional costs). So it might be reasonable to create a separate deployment pipeline that will be triggered only manually when we will want.

**Comment by bill876** [comment]
do you pay for a deploy of a lambda for some reason?
do you wanna discuss how this all works in gcp?

**Comment by VadimGush** [comment]
@bill876 Looking at the billing, its expenses a little bit higher than I calculated. The only explanation for that might be Google's use of Compute Engine for building new images... But I'm might be wrong. I think it will be better to wait until the end of the month and analyze billing once more.

**Comment by bill876** [comment]
@VadimGush can you explain in more detail? what is your estimate? how did you get it? what happens in gcp when you deploy a cloud function? where is the code to do that (i dont see it in the repo)?

available for a call or to meet irl also

**Comment by VadimGush** [comment]
@bill876 I found the issue. Cost of 0.6$ per day comes from Load Balancer (which somewhere around 15$ per month). It is not Cloud Functions or anything related to them.

**Comment by bill876** [comment]
This is exactly why it makes no sense to deploy any cloud functions for a small app unless you have a free tier for a load balancer.
For google's 0.025$/hr I can get 4 VMs with a "well-known" provider. Or 3 VMs for free with a certain less known one :)
