### ISSUE TITLE
Fail to load website in same session

### ISSUE THREAD

**Issue by harsh8051** [gush-labs/kazan#34]
I login  website with WaniKani Token 
When I logout and try to login again it redirect me desire route but component did not load properly.
When I try to reload website it shows me nothing

but when I clear Cookies or open website in incognito mode it work

Not Sure but issue might be with session 

Issue observed on Google Chrome Version 104.0.5112.101 (Official Build) (64-bit)

**Comment by VadimGush** [comment]
@harsh8051 Thanks for reporting this bug! Should be fixed now. Please verify and we will close this issue.

**Comment by harsh8051** [comment]
Yes . The issue has been fixed.
