### ISSUE TITLE
Links are still functional even if they're disabled

### ISSUE THREAD

**Issue by VadimGush** [gush-labs/kazan#40]
Because `router-link` doesn't care about "disabled" property of an HTML element, links in the web-app are still functional despite being disabled.

Steps to reproduce:
Just go to https://kana.vadimgush.com/kana/hiragana and without selecting any kana click on the button in the bottom.

**Comment by bill876** [comment]
`router-link` has nothing to do with that.
Form controls can be disabled with a `disabled` attribute, anchors (`<a>`) can not.
Try adding a `disabled` attr in dev tools - the link is still clickable.

A "disabled link" is not a link, it's just text (even if it's styled differently).
In this case it looks like if a user selected nothing, the `query.entries` is empty, so the `to` makes no sense, so constructing a `-link` `to` something also makes no sense.

If you decide that it must absolutely be a "link", you can remove `href` attr, but I'm not sure if you can do that through router-link. There are also two other hacks, but I'd rather you not doing them :) unless it's **absolutely necessary**.

**Comment by VadimGush** [comment]
@bill876 Thanks for the explanation.

**Comment by VadimGush** [comment]
By now I think it will be enough to replace such "disabled" links with just buttons.
