### ISSUE TITLE
Require npm lint to have no errors

### ISSUE THREAD

**Issue by VadimGush** [gush-labs/kazan#45]
On pull requests and any commits to the main branch, we should require code to have no error in `npm lint`

**Comment by bill876** [comment]
Added the job in #58 and made it mandatory for PRs.
However, this will not be effective against format mismatches, because they are a warning and not an error.
The good thing would be to set `--max-warnings 0`, but before that you have to fix all existing warnings.

**Comment by VadimGush** [comment]
@bill876 Thanks. I will check today how it works.
