### ISSUE TITLE
Server responses with 404 on almost any URL

### ISSUE THREAD

**Issue by VadimGush** [gush-labs/kazan#65]
Go to Chrome and enable developer tools. Open "https://kana.vadimgush.com/learning" and you will see that HTTP code was "404" despite the fact that web-app clearly has this page.

And hiragana page doesn't even open: https://kana.vadimgush.com/kana/hiragana.
<img width="560" alt="Screen Shot 2022-09-27 at 19 18 42" src="https://user-images.githubusercontent.com/6123702/192567055-b749567b-56be-460f-961a-4dd5a000f86b.png">
<img width="560" alt="Screen Shot 2022-09-27 at 19 19 33" src="https://user-images.githubusercontent.com/6123702/192567073-41874b15-a94b-4368-bd9f-83ea31092373.png">

**Comment by VadimGush** [comment]
@bill876 do you know what issue might cause that?

**Comment by bill876** [comment]
More detailed explanation of the first thing:

> despite the fact that web-app clearly has this page

It actually "clearly" doesn't.  The "app" maybe has it, but the web server (the thing that actually responds to your GET request) doesn't. It has index.html (served at `/`), some other static files served by filename, and 404.html (served for all other urls).

**Comment by bill876** [comment]
So what about the 404? If you're fine with what we have, I want to close the issue

**Comment by VadimGush** [comment]
@bill876 I'm fine with that.
