### ISSUE TITLE
Optimise app for mobile usage: icons and manifest

### ISSUE THREAD

**Issue by VadimGush** [gush-labs/kazan#66]
We should add icon in order to allow iOS and Android to add our website to the Home Screen (with normal icon, not just screenshot).

**Comment by bill876** [comment]
@VadimGush Make the svg icon and the rest is easy

**Comment by bill876** [comment]
See https://evilmartians.com/chronicles/how-to-favicon-in-2021-six-files-that-fit-most-needs
