### ISSUE TITLE
Add reachable "Go back" button for mobile client

### ISSUE THREAD

**Issue by VadimGush** [gush-labs/kazan#72]
And the phone is quite hard to reach anything which is higher than the center of the screen, so the first step to make our app a little bit easier to use on mobile is to move "Go back" link to the bottom of the screen.

**Comment by bill876** [comment]
Mobile users already have a system-wide Back button (Android) or gesture (Android and iOS). In browsers they also have a Back button from the browser.
Are these methods not enough? Is going back such a common operation in the app?

**Comment by VadimGush** [comment]
@bill876 Good point. I will discuss it with UX designer.

**Comment by VadimGush** [comment]
Ok, let's cancel this issue by now
